store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.main_page, name='home-page'),
    path('products/<int:pk>', views.ProductDetails.as_view(), name='product-details'),
    path('cart/', views.cart_view, name='cart'),
    path('cart/add-or-remove-from-cart', views.add_remove_from_cart, name='add-remove-from-cart'),
    path('shipping-address/', views.shipping_address_info, name='shipping-address'),
]

store/models.py
import random

from django.db import models
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.urls import reverse

from accounts.models import User
from accounts.utils import generate_token

from django_countries.fields import CountryField
# Create your models here.

class Image(models.Model):
    image = models.ImageField()
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='images')

    def __str__(self):
        return "image for " + self.product.name

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.FloatField()
    shipping_cost = models.FloatField()
    thumbnail = models.ImageField()

    def __str__(self):
        return self.name

    def short_name(self):
        return self.name[:15] + "..." if len(self.name)>15 else self.name

    def short_description(self):
        return self.description[:30] + '...'

class Cart(models.Model):
    products = models.ManyToManyField(Product, 'cart')
    order = models.OneToOneField('Order', null=True, on_delete=models.SET_NULL)

    def __str__(self):
        if self.order:
            return 'Cart - Order: ' + self.order.order_id
        return 'Cart' + str(self.id)

    def cart_total(self):
        total = 0
        products = self.products.all()
        for p in products:
            total += p.price
        return round(total,2)


class ShippingAddress(models.Model):
    address = models.CharField(max_length=300)
    city = models.CharField(max_length=100)
    province = models.CharField(max_length=100)
    country = CountryField(blank_label='(select country)')
    zipcode = models.IntegerField()
    user = models.ForeignKey(User, related_name='addresses', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.address + " " + self.city + ", " + self.province + " " + str(self.zipcode)  + ", " + str(self.country )


class OrderManager(models.Manager):

    def get_order_from_session(self, request):
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        order = cart.order

        return order

class Order(models.Model):
    CHOICES = (
        ('Processing', 'processing'),
        ('Paid', 'paid'),
        ('Shipping', 'shipping'),
        ('Closed', 'closed')
    )
    order_id = models.SlugField(blank=True, unique=True)
    total = models.DecimalField(default=0, max_digits=5, decimal_places=2)
    shipping_address = models.ForeignKey(ShippingAddress, related_name='order', on_delete=models.CASCADE, null=True)
    status = models.CharField(max_length=20, choices=CHOICES, default='Processing')
    user = models.ForeignKey(User, related_name='orders', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    objects = OrderManager()

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.order_id

    @property
    def subtotal(self):
        order_subtotal = 0
        try:
            for p in self.cart.products.all():
                order_subtotal += p.price
        except:
            pass
        return order_subtotal

    def get_total(self):
        total = 0
        try:
            for p in self.cart.products.all():
                total += p.price + p.shipping_cost
            return round(total, 2)
        except:
            return total

    def get_order_link(self):
        link = reverse('accounts:order-details', kwargs={'order_id':self.order_id})
        return link

@receiver(pre_save, sender=Order)
def pre_save_order(instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = generate_token(8)

    instance.total = instance.subtotal + 10.99

store/forms.py
from django import forms

from django_countries.widgets import CountrySelectWidget

from .models import ShippingAddress

class ShippingAddressForm(forms.ModelForm):

    class Meta:
        model = ShippingAddress
        fields = ('address', 'city', 'province', 'country', 'zipcode')
        widgets = {'country': CountrySelectWidget(
            layout='{widget}<img class="country-select-flag" id="{flag_id}" style="margin: 6px 4px 0;width: 20px; height: 20px;" src="{country.flag}">'
        )}

store/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseNotFound
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.http import require_GET, require_POST
from django.views.generic import DetailView

from .documents import ProductDocument
from .forms import ShippingAddressForm
from .models import Product, Cart, Order, ShippingAddress

import stripe

# Create your views here.

stripe.api_key = settings.STRIPE_SECRET

@require_GET
def main_page(request):
    q = request.GET.get('q')
    if q:
        s = ProductDocument.search().query("multi_match", query=q, fields=['name', 'description'])
        products = s.to_queryset()
    else:
        products = Product.objects.all()
    
    cart_id = request.session.get('cart_id')
    cart = None
    if cart_id:
        cart = Cart.objects.get(id=cart_id)

    context = {
        'products': products,
        'cart': cart
    }
    return render(request, 'store/home.html', context)

class ProductDetails(DetailView):
    queryset = Product.objects.all()
    template_name = 'store/product_details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        
        # this should be added to the cart manager because it's getting repetetive
        cart_id = self.request.session.get('cart_id')
    
        if cart_id:
            cart = Cart.objects.get(id=cart_id)
        else:
            cart = Cart.objects.create()
            self.request.session['cart_id'] = cart.pk
    
        context['cart'] = cart
        return context

@require_POST
def add_remove_from_cart(request):
    # get the url to redirect to, whether it's homepage or product detail
    redirect_url = request.POST.get('redirect_url')

    # get the cart id from the session storage if it exists
    cart_id = request.session.get('cart_id')

    if cart_id:
        cart = Cart.objects.get(id=cart_id)
    else:
    # if we don't have any cart id stored in the session, we add one
        cart = Cart.objects.create()
        request.session['cart_id'] = cart.id
    
    # get the product using the id provided in the url
    try:
        product_id = request.POST.get('product_id')
        product = Product.objects.get(id=product_id)
    except:
        return HttpResponseNotFound('link is broken')
        
    # add or remove product
    if product in cart.products.all():
        cart.products.remove(product)
    else:
        cart.products.add(product)

    return redirect(redirect_url)

def cart_view(request):
    cart_id = request.session.get('cart_id')
    
    if cart_id:
        cart = Cart.objects.get(id=cart_id)
    else:
        cart = Cart.objects.create()
        request.session['cart_id'] = cart.pk

    return render(request, 'store/cart.html', {'cart':cart})

# you can add the id of an existing shipping address as an argument and use the same view
# without the nedd to create another view for existing shipping addresses,
# give that argument the value of None

@login_required(login_url='/accounts/login/?next=/shipping-address/')
def shipping_address_info(request):
    
    form = ShippingAddressForm(request.POST or None)
    cart_id = request.session['cart_id']
    cart = Cart.objects.get(id=cart_id)
    order = None

    # if the user is going to use an existing shipping address
    shipping_address_id = request.POST.get('existing_address')

    if shipping_address_id:
        shipping_address = ShippingAddress.objects.get(id=shipping_address_id)
        order = Order.objects.create(
            shipping_address = shipping_address,
            user = request.user
        )
        cart.order = order
        cart.save()
        return redirect('payments:payment')
    
    # if the user decides to use a new shipping address
    if form.is_valid():
        address = form.save(commit=False)
        address.user = request.user
        address.save()
        order = Order.objects.create(
            shipping_address = address,
            user = request.user
        )
        cart.order = order
        cart.save()
        return redirect('payments:payment')

    context = {
        'form': form,
        'order': order
    }
    return render(request, 'payments/checkout.html', context)

store/templates/store/cart.html
{% include 'navbar.html' %}
{% block content %}

{% if cart.products.all%}
<div class="w-full">
    {% for product in cart.products.all %}
    <div class="grid grid-cols-4 text-xl my-1 mb-4">
        <div class="mb-1 border-r border-black border-opacity-60">
            <div><img src="{{product.thumbnail.url}}" class="h-14 w-14" alt="..."></div>
        </div>
        
        <div class="pl-4"> 
                <span ><a href="{% url 'store:product-details' product.pk %}">{{product.name}}</a></space>
        </div>
        
        <div class="pl-4 border-l border-black border-opacity-60">
            <span>{{product.price}}</span>
        </div>

        <div>
            <form action="{% url 'store:add-remove-from-cart'%}" method="post">
                {% csrf_token %}
                <input type="hidden" name="product_id" value="{{product.id}}">
                <input type="hidden" name="redirect_url" value="{{request.path}}">
                <button class="btn btn-outline-danger" type="submit"><i class="far fa fa-trash" aria-hidden="true"></i></button>
              </form>
        </div>
    </div>
    {% endfor %}

    <div class="grid grid-cols-4">
        <div class="col-end-5">
            <span>subtotal: {{cart.cart_total}}</span>
        </div>

        <div class="col-end-5">
            <a href="{% url 'store:shipping-address' %}" class='btn bg-blue-gray-600 text-white hover:bg-blue-gray-800'> checkout</a>
        </div>
    </div>
</div>

{% else %}
    <div class="flex justify-center">
        <div class="w-max">

            <div class="text-xl font-medium mt-5">
                <p>Your cart is empty</p>
            </div>
            <div class="mt-3 text-base ">
                <a href="{% url 'store:home-page' %}">Go back & Add some items?</a>
            </div>

        </div>
    </div>
{% endif %}

{% endblock %}

store/templates/store/home.html
{% extends 'navbar.html' %}
{% block content %}

  <div class="m-1 grid md:grid-cols-4 gap-10 p-3">
    {% if not products %}
    <div class="flex justify-center col-span-4">
      <span class="text-xl font-normal">Sorry, we couldn't find what you're looking for :(</span>
    </div>
    {% else %}
    {% for p in products %}
      <div class="mb-1 rounded overflow-hidden  shadow-md md:shadow-xl relative ">
          <img src="{{p.thumbnail.url}}" alt="..." class="w-full h-32 sm:h-48 object-contain">
        <div class="ml-1">
          <a href="{% url 'store:product-details' p.pk %}">
            <span>{{p.short_name}}</span>
          </a>
          <span class="block">{{p.short_description}}</span>
          <span class="font-medium">${{p.price}}</span>
          <div class="flex justify-center p-4">
            <form action="{% url 'store:add-remove-from-cart'%}" method="post">
              {% csrf_token %}
              <input type="hidden" name="product_id" value="{{p.id}}">
            {% if p in cart.products.all %}
              <input type="hidden" name="redirect_url" value="{{request.path}}">
              <button type="submit" class="inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
                remove
              </button> 
            {% else %}
              <input type="hidden" name="redirect_url" value="{{request.path}}">
              <button type="submit" class="inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500">
                Add to cart
              </button>  
            {% endif %}
          </form>
          </div>
        </div>
        <div class="font-bold bg-red-600 rounded-full text-white absolute top-0 p-1 ml-2 mt-2">
          <span> -15% </span>
        </div>
      </div>
    {% endfor %}
    {% endif %}
  </div>  

{% endblock %}

store/templates/store/product_details.html
{% extends 'navbar.html' %}

{% block content %}
<div class="flex">
    <section>
        <div>
            <img src="{{object.thumbnail.url}}" alt="" class="h-96 w-96 object-contain">
        </div>
        <div class="w-96 h-16 flex justify-evenly mt-2">
            <img src="{{object.thumbnail.url}}" alt="..." class="w-16 object-contain border border-black">
        {% for image in object.images.all %}
                <img src="{{image.image.url}}" alt="..." class="w-16 object-contain border border-black">
        {% endfor %}
        </div>
    </section>
    <main class="ml-5">
        <div>
            <span class="text-lg font-medium">{{object.name}}</span>
        </div>
        <div class="mt-4">
            <span class="font-bold text-2xl">${{object.price}}</span>
        </div>
        <div class="mt-3">
            <span class="block">Shipping cost:</span>
            <span class="mt-2 ml-1">${{object.shipping_cost}}</span>
        </div>
        <div class="mt-3 w-96">
            <span>{{object.description}}</span>
        </div>
        <div class=" mt-5">
            <form action="{% url 'store:add-remove-from-cart'%}" method="post">
                {% csrf_token %}
              {% if object in cart.products.all %}
                <a href="{% url 'store:shipping-address' %}" type="submit" class="font-medium text-base text-white p-3  bg-green-500 rounded-full hover:bg-green-600 hover:no-underline">
                  Item Already in cart, checkout?
                </a> 
              {% else %}
                <input type="hidden" name="redirect_url" value="{{request.path}}">
                <input type="hidden" name="product_id" value="{{object.id}}">
                <button type="submit" class="uppercase font-medium text-white text-lg p-3 bg-green-500 rounded-full hover:bg-green-600 hover:no-underline">
                  add to cart
                </button>  
              {% endif %}
              </form>
            <!-- <a href="#">add to cart</a> -->
        </div>
    </main>
</div>

{% endblock %}