accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.sign_in, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('settings/', views.settings_view, name='settings'),
    path('order-details/<slug:order_id>', views.OrderDetails.as_view(), name='order-details'),
    path('change-email/', views.change_email, name='change-email'),
    path('token-sent-succes/', views.token_sent_success, name='token_sent_success'),
    path('token-validation/<str:token>', views.old_token_validation, name='old-token-validation'),
    path('new-email-token', views.new_email_token, name='new-email-token'),
    path('new-token-validation/<str:token>', views.new_token_validation, name='new-token-validation'),
    path('new-email-token-sent-success', views.new_email_token_sent_success, name='new-email-token-sent-success'),
    path('new-token-validated', views.new_token_validated, name='new-token-validated'),
    path('add-shipping-address', views.add_shipping_address, name='add-shipping-address'),
    path('delete-address/<int:address_pk>', views.delete_shipping_address, name='delete-address'),
]

payments/urls.py
from django.urls import path

from . import views

app_name = 'payments'

urlpatterns = [
    path('', views.payment_view, name='payment'),
    path('charge-existing-card/<int:card_id>', views.charge_existing_card, name='charge-existing-card'),
    path('success', views.payment_success, name='payment-success'),
    path('save-card', views.save_card, name='save-card'),
    path('delete-card/<int:card_id>', views.delete_card, name='delete-card')
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.main_page, name='home-page'),
    path('products/<int:pk>', views.ProductDetails.as_view(), name='product-details'),
    path('cart/', views.cart_view, name='cart'),
    path('cart/add-or-remove-from-cart', views.add_remove_from_cart, name='add-remove-from-cart'),
    path('shipping-address/', views.shipping_address_info, name='shipping-address'),
]

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager
    )
from django.db import models
from django.db.models.signals import pre_save

from .utils import generate_token

import stripe

stripe.api_key = settings.STRIPE_SECRET

class UserManager(BaseUserManager):
    def create_user(self, email, first_name='', last_name='', password=None):
        if not email:
            raise ValueError('Email field is required')

        user = self.model(
            email = self.normalize_email(email),
            first_name=first_name,
            last_name=last_name
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name='', last_name='', password=None):
        user = self.create_user(
            email=email,
            first_name=first_name,
            last_name=last_name,
            password=password
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    email = models.EmailField(verbose_name='email address', max_length=255, unique=True)
    first_name = models.CharField(verbose_name='First Name', max_length=30, blank=True)
    last_name = models.CharField(verbose_name='Last Name', max_length=30, blank=True)
    customer_id = models.CharField(verbose_name='Customer ID', max_length=255, blank=True)
    is_active = models.BooleanField(default=True, verbose_name='Active')
    is_admin = models.BooleanField(default=False, verbose_name='Admin')

    objects = UserManager()

    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        # Does the user have a specific permission, simply, yes
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

class EmailToken(models.Model):
    token = models.CharField(max_length=255, blank=True)
    active = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='email_tokens')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.token

# sending a signal to create a stripe customer and then associating it with a user
def user_customer_id_pre_save_signal(instance, *args, **kwargs):
    if not instance.customer_id:
        customer = stripe.Customer.create(
            email = instance.email
        )
        instance.customer_id = customer.id

pre_save.connect(user_customer_id_pre_save_signal, sender=User)

# sending a signal to create the email activation token
def email_token_pre_save_signal(instance, *args, **kwargs):
    if not instance.token:
        instance.token = generate_token()

pre_save.connect(email_token_pre_save_signal, sender=EmailToken)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import User

class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput
        )

    password2 = forms.CharField(
        label='Confirm Password',
        widget=forms.PasswordInput
        )
    
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name')

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1!=password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()
    
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'is_active', 'is_admin')

    def clean_password(self):
        return self.initial['password']

class LoginForm(forms.Form):
    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(
        attrs = {
            'class': 'form-control ml-0',
        }
    ))

    password = forms.CharField(
        label='Enter Password',
        widget=forms.PasswordInput(
        attrs = {
           'class': 'form-control',
        }
    ))


class SignupForm(forms.ModelForm):
    password1 = forms.CharField(
        widget=forms.PasswordInput,
        label='Password'
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput,
        label='Confirm Password'
    )

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name']


    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match please try again")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

class UserChangeForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name']

accounts/views.py
from ecommerce.settings import EMAIL_HOST_USER, EMAIL_HOST_PASSWORD

from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse
from django.views.decorators.http import require_POST
from django.views.generic.detail import DetailView

from .forms import LoginForm, SignupForm, UserChangeForm
from .models import User, EmailToken

from store.models import Order, ShippingAddress
from store.forms import ShippingAddressForm
# Create your views here.

# the reason i named it like that is because login is the name of the function
# used to log the user in
def sign_in(request):
    if request.user.is_authenticated:
        return redirect('/')

    redirect_url = request.POST.get('next') or '/'

    form = LoginForm(request.POST or None)
    if form.is_valid():
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        user = authenticate(request, email=email, password=password)
        if user:
            login(request, user)
            return redirect(redirect_url)
        form.add_error(
            field = 'email',
            error = 'error: please make sure that you provided the right credentials'
        )
    return render(request, 'accounts/login.html', {'form': form})


def register(request):
    if request.user.is_authenticated:
        return redirect('store:home-page')
    form = SignupForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        return redirect('accounts:login')
    return render(request, 'accounts/register.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('accounts:login')


def settings_view(request):
    form = UserChangeForm(instance=request.user)
    shipping_address_form = ShippingAddressForm()
    if request.method == 'POST':
        form = UserChangeForm(request.POST, instance=request.user)
        print(form)
        if form.is_valid():
            user = form.save(commit=False)
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.save()
            return redirect('accounts:settings')
        else:
            return HttpResponse('inalid form')
    context = {
        'form': form,
        'shipping_address_form': shipping_address_form
    }
    return render(request, 'accounts/settings.html', context)


@require_POST
@login_required(login_url='/account/login')
def change_email(request):
    user = request.user  
    t = EmailToken.objects.create(user=user)
    host = request.get_host()
    path = reverse('accounts:old-token-validation', kwargs={'token': t})
    old_email_confirmation_link = f'http://{host}{path}'
    recipient = request.user.email

    send_mail(
        subject = 'request for changing email',
        message = 'I do not know how is this gonna be displayed',
        html_message = f'hey {request.user.first_name}, you requested changing your email, click on this link to proceed, <a href="{old_email_confirmation_link}" target="_blank"> click here </a>',
        from_email = EMAIL_HOST_USER,
        recipient_list = [recipient],
        fail_silently=False,
        )

    return redirect('accounts:token_sent_success')

@login_required(login_url='/account/login')
def token_sent_success(request):
    email = request.user.email
    return render(request, 'accounts/token_sent_success.html', {'email':email})

@login_required(login_url='/account/login')
def old_token_validation(request, token):
    # get the token from the url argument and look it up using the token string
    # if it's active, deactivate it, and redirect to entering new email view
    try:
        token_obj = EmailToken.objects.get(token=token)
        if token_obj.active:
            token_obj.active = False
            token_obj.save()
            return render(request, 'accounts/token_validated.html')
    except Exception as error:
        return render(request, 'accounts/token_error.html', {'error':error})

# when you get back from the gym, make the view to send the new email token, one to confirm it and change the email, and one to say
# the operation was successful

@require_POST
@login_required(login_url='/account/login')
def new_email_token(request):
    recipient = request.POST.get('email')

    # try if the new email is already taken
    try:
        email_exists = User.objects.get(email=recipient)
        return HttpResponse('this email is taken, please try again')
    except:
        pass

    user = request.user  
    t = EmailToken.objects.create(user=user)
    host = request.get_host()
    path = reverse('accounts:new-token-validation', kwargs={'token': t})
    new_email_confirmation_link = f'http://{host}{path}'

    send_mail(
        subject = 'new email confirmation',
        message = 'I do not know how is this gonna be displayed',
        html_message = f'hey {request.user.first_name}, you requested changing your email, click on <a href="{new_email_confirmation_link}" target="_blank"> this link </a> to confirm your new email',
        from_email = EMAIL_HOST_USER,
        recipient_list = [recipient],
        fail_silently=False,
        )

    request.session['email'] = recipient

    return redirect('accounts:new-email-token-sent-success')

@login_required(login_url='/account/login')
def new_email_token_sent_success(request):
    email = request.session['email']
    return render(request, 'accounts/new-email-token-sent-success.html', {'email':email})

@login_required(login_url='/account/login')
def new_token_validation(request, token):
    try:
        token_obj = EmailToken.objects.get(token=token)
        user = request.user
        if token_obj.active:
            token_obj.active = False
            token_obj.save()
            user.email = request.session['email']
            user.save()
            del request.session['email']
            return render(request, 'accounts/new-token-validated.html')
    except Exception as error:
        return render(request, 'accounts/token_error.html', {'error': error})

@login_required(login_url='/account/login')
def new_token_validated(request):
    return render(request, ('accounts/new-token-validated.html'))

class OrderDetails(DetailView):
    model = Order
    slug_field = 'order_id'
    slug_url_kwarg = 'order_id'
    template_name = 'accounts/order_details.html'


# try to figure out how to do it with CBVs
@require_POST
def add_shipping_address(request):
    form = ShippingAddressForm(request.POST)
    if form.is_valid():
        address = form.save(commit=False)
        address.user = request.user
        address.save()
        return redirect('accounts:settings')

@require_POST
def delete_shipping_address(request, address_pk):
    address = ShippingAddress.objects.get(pk=address_pk)
    address.delete()
    redirect_path = request.POST.get('redirect_path')
    return redirect(redirect_path)

accounts/templates/accounts/login.html
{% include 'navbar.html' %}

{% block content %}
<div class="col-4 mx-auto my-5 border border-primary px-5 py-5 ">
    <form action="{% url 'accounts:login' %}" method="post">
        {% if form.errors %}
            <div class="bg-red-100 border-2 border-red-600 text-red-800 rounded-full p-4 m-2" name='error_messages'>
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}
            </div>
        {% endif %}
        {% csrf_token %}
        <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        {{form.email}}
        </div>
        <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        {{form.password}}
        </div>
        <input type="hidden" name="next", value="{{request.GET.next}}">
        <button type="submit" class="btn btn-primary my-3">Login</button>
    </form>
    <a class='btn btn-link' href="{% url 'accounts:register' %}">don't have an account?</a>
</div> 
{% endblock %}

accounts/templates/accounts/new-email-token-sent-success.html
{% extends 'navbar.html' %}

{% block content %}

<h1>verification link has been sent</h1>

<h5 class="col mx-auto">An email with a verification link has been sent to {{email}}, please check your inbox</h5>

{% endblock %}

accounts/templates/accounts/new-token-validated.html
{% extends 'navbar.html' %}

{% block content %}

<h1>Your email has been updated successfully </h1>

{% endblock %}

accounts/templates/accounts/order_details.html
{% extends 'navbar.html' %}

{% block content %}
<div class="container-fluide">
  <div class="row col-12">
      <div class="col-12 mb-4 mx-auto" >
          <h3 class="col-3 mt-3 mx-auto">
            Products ordered:
          </h3>
      </div>
    {% for p in order.cart.products.all %}
      <div class="col-3 ">
            <div class="card" style="width: 14rem;">
              <img src="{{p.thumbnail.url}}" class="card-img-top mx-auto" alt="..." style="width: 100%;height: 12em;">
              <div class="card-body">
                <h5 class="card-title">{{p.name}}</h5>
                <p class="card-text">{{p.short_description}}</p>
                <h6 class="card-title">${{p.price}}</h6>
              </div>
            </div>
      </div>
    {% endfor %}
    </div>
    <hr>
    <div class="row col">
      <h5 class="col mx-auto">order total: {{order.get_total}}</h5>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% include 'navbar.html' %}

{% block content %}
<div class="col-8 mx-auto my-5 border border-primary px-5 py-5 ">
    <form action="" method="post" class="mt-4 w-min">
        {% csrf_token %}
        <div class="w-max">
          {% for field in form %}
            <div class="flex justify-between my-1">
              {{field.errors}}
              {{field.label_tag}}
              <div class="ml-4 flex justify-evenly">{{field}}</div>
            </div>
          {% endfor %}
        </div>
            <button type="submit" class="btn btn-primary">Add address</button>
        </form>
    <a href="{% url 'accounts:login' %}" class="btn btn-link">already have an account?</a>
</div>
{% endblock %}

accounts/templates/accounts/settings.html
{% extends 'navbar.html' %}

{% block content %}

<div class="row">
    <div class="col-4">
      <div class="list-group" id="list-tab" role="tablist">
        <a class="list-group-item list-group-item-action active" id="personal-info-list" data-toggle="list" href="#personal-info" role="tab" aria-controls="home">Personal info</a>
        <a class="list-group-item list-group-item-action" id="email-list" data-toggle="list" href="#email" role="tab" aria-controls="profile">Email</a>
        <a class="list-group-item list-group-item-action" id="orders-list" data-toggle="list" href="#orders" role="tab" aria-controls="messages">Orders</a>
        <a class="list-group-item list-group-item-action" id="addresses-list" data-toggle="list" href="#addresses" role="tab" aria-controls="settings">Addresses</a>
        <a class="list-group-item list-group-item-action" id="cards-list" data-toggle="list" href="#cards" role="tab" aria-controls="settings">payment cards</a>
      </div>
    </div>
    <div class="col-8">
          <div class="tab-content" id="nav-tabContent">
          <div class="tab-pane fade show active" id="personal-info" role="tabpanel" aria-labelledby="personal-info-list">
            <form action="{% url 'accounts:settings' %}" method="post">
              {% csrf_token %}
              {{form.first_name.label_tag}}
              {{form.first_name}}
              {{form.last_name.label_tag}}
              {{form.last_name}}
              <button class="btn btn-primary"> update personal info </button>
            </form>
          </div>

      <!-- Change Email -->
        <div class="tab-pane fade" id="email" role="tabpanel" aria-labelledby="email-list">
          <form action="{% url 'accounts:change-email' %}" method="post">
            {% csrf_token %}
            <label for="email">Email:</label>
            <input type="email" name="email" id="email" value="{{request.user.email}}" disabled>
            <button class="btn btn-primary"> change email </button>
          </form>          
        </div>

        <!-- Orders -->
        <div class="tab-pane fade" id="orders" role="tabpanel" aria-labelledby="orders-list">
          <table class="table table-hover my-3">
            <thead class="thead-dark">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Order ID</th>
                <th scope="col">Order Total</th>
                <th scope="col">Order Date</th>
              </tr>
            </thead>
            <tbody>
              {% for order in request.user.orders.all %}
              <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td> <a href="{{order.get_order_link}}" class="btn-link"> {{order.order_id}} </a> </td>
                <td>{{order.get_total}}</td>
                <td>{{order.created}}</td>
              {% endfor %}
          </table>
        </div>

        <div class="tab-pane fade" id="addresses" role="tabpanel" aria-labelledby="addresses-list">
          

            <table class="table table-hover my-3 table-borderless">
              <thead class="thead-light">
                <tr>
                  <th scope="col" >#</th>
                  <th scope="col" >Address Line</th>
                </tr>
                  {% for a in request.user.addresses.all %}
                  <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{a.address}} - {{a.city}}/{{a.province}} - {{a.country}} </td>
                    <td>
                      <form action="{% url 'accounts:delete-address' a.id %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-outline-danger" type="submit"> <i class="far fa-times-circle" size='5'></i> </button>
                        <input type="hidden" name="redirect_path" value="{{ request.path }}">
                      </form>
                    </td>
                  </tr>
                  {% endfor  %}
              </thead>
            </table>
            <hr>

            <!-- Button trigger modal  - adding a new address button -->
            <button type="button" class="btn btn-info" data-toggle="modal" data-target="#exampleModalCenter">
              Add new shipping address
            </button>

            <!-- Modal - adding a new address form -->
            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">Enter new address information</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <div class="border-b border-black pb-3">
                      <form action="{% url 'accounts:add-shipping-address' %}" method="post" class="mt-4 w-min">
                        {% csrf_token %}
                        <div>
                          {% for field in shipping_address_form %}
                            <div class="flex justify-between my-1">
                              {{field.errors}}
                              {{field.label_tag}}
                              <div class="ml-4 flex justify-evenly">{{field}}</div>
                            </div>
                          {% endfor %}
                        </div>
                     
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          <button type="submit" class="btn btn-primary">Add address</button>
                        </div>
                     
                      </form>
                   </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- End Modal -->

        </div>
        <div class="tab-pane fade" id="cards" role="tabpanel" aria-labelledby="cards-list">
          
          <!-- Card choices -->
          <div class="row">
            <div class="col-sm-6">
              {% for c in request.user.cards.all %}
              <div class="card my-3">
                <div class="card-body">
                  <h5 class="card-title">
                    {% for i in 'twelve chars' %}
                    <i class="fas fa-circle"></i>
                      {% if forloop.counter|divisibleby:"4" %}
                        &#160;
                      {% endif %}
                    {% endfor %}
                    {{c.last_4}}
                  </h5>
                  <h5 class="card-title"><i class="fab fa-cc-{{c.brand}}"></i></h5>
                  <form action="{% url 'payments:delete-card' c.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                  </form>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/token_error.html
{%  extends 'navbar.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col mx-auto ">
            <h1> Sorry, this page is unavailable </h1>
            <h5>Wrong verification link, please try another one <br>Error message: {{error}}</h5>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/token_sent_success.html
{% extends 'navbar.html' %}

{% block content %}

<h1>verification link has been sent</h1>

<h5 class="col mx-auto">An email with a verification link has been sent to {{email}}, please check your inbox</h5>

{% endblock %}

accounts/templates/accounts/token_validated.html
{% extends 'navbar.html' %}

{% block content %}

{% if error%}
    <div class="col">
        <h1 class="col mx-autot">{{error}}</h1>
    </div>
{% else %}

<div class="col col-center">
    <h1>Your email has been confirmed</h1>
    <h3> please enter a new email for your account</h3>
    <form action="{% url 'accounts:new-email-token' %}" method="post">
        {% csrf_token %}
        <label for="email">Enter new email:</label>
        <input type="email" name="email" id="email">
        <button class="btn btn-primary" type="submit">send confirmation link</button>
    </form>
</div>

{% endif %}

{% endblock %}