payments/urls.py
from django.urls import path

from . import views

app_name = 'payments'

urlpatterns = [
    path('', views.payment_view, name='payment'),
    path('charge-existing-card/<int:card_id>', views.charge_existing_card, name='charge-existing-card'),
    path('success', views.payment_success, name='payment-success'),
    path('save-card', views.save_card, name='save-card'),
    path('delete-card/<int:card_id>', views.delete_card, name='delete-card')
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.main_page, name='home-page'),
    path('products/<int:pk>', views.ProductDetails.as_view(), name='product-details'),
    path('cart/', views.cart_view, name='cart'),
    path('cart/add-or-remove-from-cart', views.add_remove_from_cart, name='add-remove-from-cart'),
    path('shipping-address/', views.shipping_address_info, name='shipping-address'),
]

payments/models.py
from django.db import models

from accounts.models import User

# Create your models here.


class Card(models.Model):
    brand = models.CharField(max_length=20)
    last_4 = models.IntegerField()
    fingerprint = models.CharField(max_length=100)
    payment_method = models.CharField(max_length=100)
    user  = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cards')

    def __str__(self):
        return self.brand + ': ' + str(self.last_4)

payments/views.py
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import DeleteView

import json

from .models import Card

from store.models import Cart, Order

# Stripe
import stripe

stripe.api_key = settings.STRIPE_SECRET

# Create your views here.


def payment_view(request):
    order = Order.objects.get_order_from_session(request)

    if order.status != 'Processing':
        return redirect('store:payment-success')
 
    if request.method == 'POST':
        try:
            total = int(order.get_total() * 100)
            intent = stripe.PaymentIntent.create(
                amount = total,
                currency = 'usd',
                customer = request.user.customer_id,
                receipt_email = request.user.email,
            )
            return JsonResponse({
            'clientSecret': intent['client_secret']
            })
        except Exception as e:
            return JsonResponse({'error': str(e)})


    return render(request, 'payments/checkout.html', {'order':order})

@require_POST
def charge_existing_card(request, card_id):
    order = Order.objects.get_order_from_session(request)

    card = Card.objects.get(id=card_id)

    intent = stripe.PaymentIntent.create(
        amount = int(order.get_total() * 100),
        currency = 'usd',
        customer = card.user.customer_id,
        payment_method = card.payment_method,
        off_session=True,
        confirm=True,
    )
    return redirect('payments:payment-success')

@require_POST
def save_card(request):
    try:
        post_data = json.loads(request.body.decode('utf-8'))
        payment_method_id = post_data['payment_method']
        pm = stripe.PaymentMethod.retrieve(id=payment_method_id)
        new_card = pm['card']
        user_cards = request.user.cards.all()
        if not user_cards.filter(fingerprint=new_card['fingerprint']):
            card = Card.objects.create(
                brand = pm['card']['brand'],
                last_4 = pm['card']['last4'],
                fingerprint = pm['card']['fingerprint'],
                payment_method = pm['id'],
                user = request.user
            )
            stripe.Customer.modify(
                card.user.customer_id,
                invoice_settings={'default_payment_method': payment_method_id}
            )
            return JsonResponse({
                'message': 'Card has been successfully saved'
            })

        else:
            return JsonResponse({
                'error_message': 'Card already exists'
            })

    except Exception as e:
        return JsonResponse({'error': str(e)})

# deleting a card should also send a request to stripe to detatch the card from the customer
def delete_card(request, card_id):
    card = Card.objects.get(id=card_id)
    stripe.PaymentMethod.detach(
        card.payment_method
    )
    card.delete()
    return redirect('accounts:settings')


def payment_success(request):
    order = Order.objects.get_order_from_session(request)

    if order.status == 'Processing':
        order.status = 'Paid'
        order.save()
        del request.session['cart_id']

    return render(request, 'payments/checkout.html', {'order': order})

payments/templates/payments/checkout.html
{% load static %}
{% include 'navbar.html' %}

{% block content %}

{% if not order.shipping_address %}

<div class="flex justify-center mt-5">
    <div class="w-min mx-auto">

        <div class="w-max flex justify-center ">
            <h1 class="text-3xl">Please, Enter your shipping address</h1>
        </div>
        <div class="border-b border-black pb-3">
          <form action="" method="post" class="mt-4 w-min">
            {% csrf_token %}
            <div>
              {% for field in form %}
                <div class="flex justify-between my-1">
                  {{field.errors}}
                  {{field.label_tag}}
                  <div class="ml-4 flex justify-evenly">{{field}}</div>
                </div>
              {% endfor %}
            </div>
            <button class="btn btn-primary" type="submit">Proceed to checkout</button>
        </form>
        </div>

        <!-- Existing shipping address -->
        {% if request.user.addresses.all %}
        <div class="w-max flex justify-center mt-2">
          <h1 class="text-3xl">Or, use an existing one</h1>
        </div>
        <div class="mt-4">
          <form action="{% url 'store:shipping-address' %}" method="post">
            {% csrf_token %}
            {% for a in request.user.addresses.all %}
                <input class="form-check-input" type="radio" name="existing_address" id="id_{{a.id}}" value="{{a.id}}" checked>
                <label class="form-check-label" for="id_{{a.id}}"> {{a.address}} </label>
                <br>
            {% endfor %}
            <br>
            <button class="btn btn-success" type="submit">choose address</button>
        </form>
      </div>
        {% endif %}
    </div>
</div>

{% elif order.status == 'Processing' %}

    {% block stripe %}
        <!-- Stripe  -->
        <link rel="stylesheet" href="{% static 'store/global.css' %}" />
        <script src="https://js.stripe.com/v3/"></script>
        <script src="{% static 'store/client.js' %}" defer></script>
    {% endblock %}

<div class="flex justify-between">

  <!-- Charge existing card  -->
          <div class="">
            <div class="text-3xl m-3">
              <p>Use an existing card</p>
            </div>
            {% for c in request.user.cards.all %}
            <div class="card my-3 w-max ml-3">
              <div class="card-body">
                <div class="">
                  <h5 class="card-title">
                    {% for i in 'twelve chars' %}
                    <i class="fas fa-circle"></i>
                      {% if forloop.counter|divisibleby:"4" %}
                        &#160;
                      {% endif %}
                    {% endfor %}
                    {{c.last_4}}
                  </h5>
                </div>
                <p class="card-title text-3xl"><i class="fab fa-cc-{{c.brand}}"></i></p>
                <form action="{% url 'payments:charge-existing-card' c.id %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-success">Pay</button>
                </form>
              </div>
            </div>
            {% endfor %}
          </div>

  <div class="text-xl my-auto">
    <h1>Or</h1>
  </div>

        <!-- Add a new card -->
  <div>
    <div class="text-3xl m-3">
      <p>Add a new card</p>
    </div>
    <div>
      <form id="payment-form">
          <input type="hidden" id="redirect-url" value="{% url 'payments:payment-success'%}">
          <div id="card-element"><!--Stripe.js injects the Card Element--></div>
          <button id="submit">
            <div class="spinner hidden" id="spinner"></div>
            <span id="button-text">Pay</span>
          </button>
          <p id="card-error" role="alert"></p>
          <p class="result-message hidden">
            Payment succeeded
          </p>
      </form>
    </div>
  </div>

</div>

<!-- Order review -->
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle flex justify-center w-max sm:px-6 lg:px-8">
     
      <!-- Table  -->
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">

        <div class="text-xl font-medium ml-8">
          <p>Order review:</p>
        </div>

        <table class="w-min divide-y divide-gray-200">

          <tbody class="bg-white divide-y divide-gray-200">
            {% for p in order.cart.products.all %}
            <tr>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="flex-shrink-0 h-10 w-10">
                    <img class="h-12 w-12 rounded-full" src="{{p.thumbnail.url}}" alt="">
                  </div>
                  <div class="ml-4">
                    <div class="text-sm font-medium text-gray-900">
                      <a href="{% url 'store:product-details' p.pk %}">{{p.name}}</a>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  ${{p.price}}
                </div>
              </td>
            </tr>
            {% endfor %}
            <tr>
              <td></td>
              <td>
                <div class="felx items-center mt-2 font-medium w-max mr-3">
                    subtotal: ${{order.subtotal}}
                </div>
              </td>
            </tr>
            <tr>
              <td></td>
              <td>
                <div class="felx items-center mt-2 font-medium text-base">
                    total: ${{order.get_total}}
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <!-- End of table  -->

      <!-- Shipping Address -->
      <div class="ml-24">
        <div class="text-xl font-medium">Shipping Address:</div>
        <div>
          {{order.shipping_address}}
        </div>
      </div>
      <!-- End of Shipping Address -->
    </div>
  </div>
</div>

{% else %}
<div class="flex justify-center">
  <div class="w-max">
    <p class="font-bold text-2xl">Thank you for your order</p>
  </div>
</div>
{% endif%}

{% endblock %}