accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.sign_in, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('settings/', views.settings_view, name='settings'),
    path('order-details/<slug:order_id>', views.OrderDetails.as_view(), name='order-details'),
    path('change-email/', views.change_email, name='change-email'),
    path('token-sent-succes/', views.token_sent_success, name='token_sent_success'),
    path('token-validation/<str:token>', views.old_token_validation, name='old-token-validation'),
    path('new-email-token', views.new_email_token, name='new-email-token'),
    path('new-token-validation/<str:token>', views.new_token_validation, name='new-token-validation'),
    path('new-email-token-sent-success', views.new_email_token_sent_success, name='new-email-token-sent-success'),
    path('new-token-validated', views.new_token_validated, name='new-token-validated'),
    path('add-shipping-address', views.add_shipping_address, name='add-shipping-address'),
    path('delete-address/<int:address_pk>', views.delete_shipping_address, name='delete-address'),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.main_page, name='home-page'),
    path('products/<int:pk>', views.ProductDetails.as_view(), name='product-details'),
    path('cart/', views.cart_view, name='cart'),
    path('cart/add-or-remove-from-cart', views.add_remove_from_cart, name='add-remove-from-cart'),
    path('shipping-address/', views.shipping_address_info, name='shipping-address'),
]

templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
   
    <!-- Boostrap JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <!-- font awesome -->
    <script src="https://kit.fontawesome.com/95f2ede694.js" crossorigin="anonymous"></script>    
    {% block stripe %}

    {% endblock %}


    <!-- TailwindCSS -->
    <link rel="stylesheet" href="{% static 'styles.css' %}" type="text/css">

</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <!-- <a class="navbar-brand" href="#">Logo</a> -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'store:home-page' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        
        <li class="nav-item dropdown">
        {% if request.user.is_authenticated %}
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'accounts:settings' %}">account settings</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
            </div>
        {% endif %}
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{% url 'store:cart' %}" tabindex="-1" ><i class="fas fa-shopping-cart"></i> {{cart.products.count}} </a>
        </li>
        {% if not request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>
        {% endif %}
        </ul>
        <form action="{% url 'store:home-page' %}" method="GET" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
            <button class="my-2 my-sm-0 p-2 text-white text-base bg-blue-700 rounded-md hover:bg-blue-800" type="submit">Search</button>
        </form>
    </div>
    </nav>

        {%block content%}
        {%endblock%}
    
</body>
</html>